### PR TITLE
Change to "Happy publishing." per change in core

### PR DESCRIPTION
**Pull request by danielbachhuber**
Related https://github.com/wp-cli/config-command/issues/81

### CODE REVIEW

**Comment by schlessera** [comment]
Test failure unrelated, might be a temporary, restarting...

**Comment by danielbachhuber** [comment]
Restarted again.

**Comment by danielbachhuber** [comment]
Ah, there's actually a problem!

```
$ wget http://wordpress.org/nightly-builds/wordpress-4.9-latest.zip
--2019-01-14 11:38:49--  http://wordpress.org/nightly-builds/wordpress-4.9-latest.zip
Resolving wordpress.org (wordpress.org)... 198.143.164.252
Connecting to wordpress.org (wordpress.org)|198.143.164.252|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://wordpress.org/nightly-builds/wordpress-4.9-latest.zip [following]
--2019-01-14 11:38:50--  https://wordpress.org/nightly-builds/wordpress-4.9-latest.zip
Connecting to wordpress.org (wordpress.org)|198.143.164.252|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-14 11:38:50 ERROR 404: Not Found.
```

**Comment by danielbachhuber** [comment]
89e483b81add13746b0b3f94a293699cc36a7f01 fixed it

**Pull request merged**
