### PR TITLE
Update scaffolded README and GitHub configuration

### PR DESCRIPTION
**Pull request by danielbachhuber**
* Regenerates README.md
* Adds `.github/settings.yml` for description and label management.
* Updates `.github/PULL_REQUEST_TEMPLATE`

### CODE REVIEW

**Comment by gitlost** [comment]
There seems to be intermittent problems when accessing "https://api.wordpress.org/core/checksums/1.0/" (SSL) in WP's `get_core_checksums()` - I'll do a PR to ignore the `trigger_error` PHP notice.

**Comment by danielbachhuber** [comment]
I was going to comment on the type hints but then I let it fly...

**Comment by gitlost** [comment]
> I was going to comment on the type hints but then I let it fly...

Yeah I stupidly copy/pasted the args from php.net, didn't even notice the hints.

**Comment by gitlost** [comment]
Now there seems to be intermittent issues with `https://wordpress.org`, build https://travis-ci.org/wp-cli/core-command/jobs/305278606

`wp core download --version=4.3.2 --force` in "features/core-download.feature:179":

`Failed to get url 'https://wordpress.org/wordpress-4.3.2.tar.gz': cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received.`

**Pull request merged**
