### PR TITLE
Removing single point of failure from download function while looking for existing wordpress installation

### PR DESCRIPTION
**Pull request by anirudhdggl**
This pull request resolves the issue of single point of failure for checking an existing WordPress installation as in issue #164

### CODE REVIEW

**Comment by schlessera** [comment]
Thanks for the PR, @anirudhdggl !

I'm afraid this check is too vague, though. For example, it will match `wp-content`, which is often the only thing stored in version-control systems, and that can often be found separate from a WP core installation.

With this check, something cloning their site's `wp-content` and then wanting to install Core to go along with it would have WP-CLI erroneously believe Core is already installed.

**Comment by anirudhdggl** [comment]
That's an interesting thing to consider, and honestly a great thing that I learnt today. Maybe I should make this check particular to the files that any normal user would not interact with like wp-load.php, wp-cron.php, wp-mail.php and wp-links-opml.php

**Comment by anirudhdggl** [comment]
I can't understand why it's failing tests while updating wordpress :thinking:

**Comment by wojsmol** [comment]
@anirudhdggl Please merge latest master top your branch.

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/9b137817e119321f03b9d09df855b3fb in case this PR is auto-closed or broken in some way.

**Pull request closed without merging**
